texthub/managehub/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from managehub.models import *
from django.utils import timezone


urlpatterns = patterns('',
    url(r'^index','managehub.views.index',name='index'),
    url(r'^uploadify_script/', 'uploadify_script',name="uploadify_script"),

)

texthub/texthub/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from views import *
admin.autodiscover()
urlpatterns = patterns('',
	url(r'^$', home),
	url(r'^essay/(?P<eid>\d+)/$','managehub.views.essay_details',name='essay_details'),
	url(r'^search/$','managehub.views.search',name='search'),
	url(r'^logo/$','managehub.views.login_view',name='login_view'),
	url(r'^logoout/$','managehub.views.logout_view',name='logout_view'),
	url(r'^publish/','managehub.views.publish',name='publish'),
	url(r'^mulpulish/','managehub.views.mulpulish',name='mulpulish'),
	url(r'^delete/(?P<eid>\d+)/$','managehub.views.delete',name='delete'),
	url(r'^save/(?P<eid>\d+)/$','managehub.views.save',name='save'),
	url(r'^mody/(?P<eid>\d+)/$','managehub.views.mody',name='mody'),
	url(r'^etype/(?P<etype>\d+)/$','managehub.views.index'),
	url(r'^fabu/$','managehub.views.fabu'),
	url(r'^uploadify_script/', 'managehub.views.uploadify_script',name="uploadify_script"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/',include('tinymce.urls')),
)
urlpatterns += patterns('managehub.views',
    url(r'^managehub/',include('managehub.urls',namespace="managehub")),
)

texthub/managehub/models.py
# -*- coding:utf-8 -*-  
from django.db import models 

#文章类型列表     
class EssayType(models.Model):  
    id=models.AutoField('id',primary_key=True)  
    #相当于varchar字符类型,最大长度25  
    tname=models.CharField(  
    verbose_name='文章类名',max_length=25)  
    baseType=models.ForeignKey('self','id',  
    null=True, blank=True,  
    verbose_name='所属类别')  
    #重写Meta模块,修改在管理后台中的显示名称  
    class Meta:  
        verbose_name = '文章类型'  
        verbose_name_plural = '文章类型列表'  
        #按名称排序  
        ordering = ['tname']  
    def __unicode__(self):  
        return self.tname  
#文章列表,verbose_name就是等下再后台中字段的名称        
class Essay(models.Model):
    id=models.AutoField('id',primary_key=True)   
    eType=models.ForeignKey(EssayType,  
    verbose_name='所属类别')
    title=models.CharField(max_length=25,  
    verbose_name='文章标题')  
    content=models.TextField(max_length=2000,  
    verbose_name='文章内容')  
    pub_date=models.DateTimeField(  
    verbose_name='发表日期')  
    view_count=models.IntegerField(  
    verbose_name='浏览次数',default=0)  
    class Meta:  
        verbose_name = '文章'  
        verbose_name_plural = '文章列表'  
        #按时间排序  
        ordering = ['-pub_date']  
    def __unicode__(self):  
        return self.title   

texthub/managehub/views.py
#coding=utf-8
from django.http import HttpResponse,HttpResponseRedirect
from django.template import Context, loader
from managehub.models import *
from django.http import Http404
from django.core.urlresolvers import reverse
from django.shortcuts import render,get_object_or_404,render_to_response 
import datetime  
from PIL import ImageFile
import os,uuid,glob
from django.conf import settings
from django.db.models import Q  
from django.core.context_processors import csrf
from django.views.decorators.csrf import csrf_protect,csrf_exempt
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required


logoUser=None
superuser=None
temp=None
classs_list=["交通","体育","军事","医药","政治","教育","环境","经济","艺术","计算机"]

@csrf_protect
@login_required
def index(request,etype=None,keyword=None):  
    try:  
        etype=int(etype)  
    except:  
        etype=None 
    if temp and keyword:
        datas=Essay.objects.all().filter(eType=temp).filter(Q(title__icontains=keyword)|Q(content__icontains=keyword)).distinct()
        global temp
        temp=None   
    elif etype:  
        datas=Essay.objects.all().filter(eType=etype)
        global temp
        temp=etype
    elif keyword:  
        datas=Essay.objects.all().filter(Q(title__icontains=keyword)|Q(content__icontains=keyword)).distinct() 
    else:  
        datas=Essay.objects.all()
    viewsList=datas.order_by('-view_count')[:5] 
    detaillist=datas.order_by('-pub_date')[:10] 
    detaillist2=datas.order_by('-pub_date') 
    if keyword or etype :
        context={
            'super':superuser,
            'user':logoUser,
            'essaydetails':detaillist2,
            'essay_type':EssayType.objects.all(),  
            'vies':viewsList}
        context.update(csrf(request))
    else:
        context={
            'super':superuser,
            'user':logoUser,
            'essaydetails':detaillist,
            'essay_type':EssayType.objects.all(),  
            'vies':viewsList}
        context.update(csrf(request))
    return render_to_response('managehub/index.html',context)
#文章详细信息
@csrf_protect
def essay_details(request,eid=None):
    #返回文章详细信息或者404页面
    essay=get_object_or_404(Essay,id=eid)
    #新用户的Session
    if request.session.get('e'+str(eid),True):
        request.session['e'+str(eid)]=False
        #这里可以用一个timer实现，浏览次数保存在内存中，
        #timer定期将浏览次数提交到数据库
        #文章浏览次数+1
        essay.view_count=essay.view_count+1
        essay.save()
    viewsList=Essay.objects.all().order_by('-view_count')[:5]
    context={
    'essay':essay,
    'user':logoUser,
    'essay_type':EssayType.objects.all(),
    'date_format':essay.pub_date.strftime('%A %B %d %Y').split(),
    'vies':viewsList
    }
    context.update(csrf(request))
    return render_to_response('managehub/details.html',context)
#根据关键字来搜索文章    
def search(request):
    if request.method == 'POST':
        #从POST请求中获取查询关键字
        key=request.POST.get('keyword',None)
        return index(request,keyword=key)
    else:
        return index(request)
#删除文章
def delete(request,eid=None):
    essay=Essay.objects.get(id=eid)
    essay.delete()
    return index(request)
    return index(request)
#更新文章
def mody(request,eid=None):
    essay=get_object_or_404(Essay,id=eid)
    #新用户的Session
    if request.session.get('e'+str(eid),True):
        request.session['e'+str(eid)]=False
        #这里可以用一个timer实现，浏览次数保存在内存中，
        #timer定期将浏览次数提交到数据库
        #文章浏览次数+1
        essay.view_count=essay.view_count+1
        essay.save()
    datas=Essay.objects.all()
    viewsList=datas.order_by('-view_count')[:5]   
    context={
            'essay':essay,
            'user':logoUser,
            'essaydetails':datas.order_by('-pub_date'),
            'essay_type':EssayType.objects.all(),  
            'vies':viewsList}
    context.update(csrf(request))
    return render_to_response('managehub/mody.html',context)
#保存更新
def save(request,eid=None):
    essay=get_object_or_404(Essay,id=eid)
    if request.method == 'POST':
        title=request.POST.get('MTITLE',None)
        content=request.POST.get('MCONTENT',None)
        if title and content :
            essay.title=title
            essay.content=content
            essay.pub_date=datetime.datetime.now()
            essay.save()
            return index(request)
        return HttpResponse('error1.')
    return HttpResponse('请勿重复提交')


#发布信息
def publish(request):
    if request.method == 'POST':
        title=request.POST.get('TITLE',None)
        content=request.POST.get('ECONTENT',None)
        etypename=request.POST.get('ETYPE',None)
        if etypename == u'\u81ea\u52a8\u5206\u7c7b':
            etypeid=classify(content)
            etypename=classs_list[etypeid]
        if etypename == u'\u672a\u9009\u62e9':
            newtype=EssayType()
            newtype.tname=request.POST.get('Newtype',None)
            newtype.save()
            etypename=newtype.tname
        etype=EssayType.objects.get(tname=etypename)
        if title and content and etype :
            essay=Essay()
            essay.title=title
            essay.content=content
            essay.eType=etype
            essay.pub_date=datetime.datetime.now()
            essay.save()
            return index(request)
        return HttpResponse('error1.')
    return HttpResponse('请勿重复提交')
def fabu(request):
    template = loader.get_template('managehub/fabu.html')
    viewsList=Essay.objects.all().order_by('-view_count')[:5]
    path=os.path.join(settings.MEDIA_ROOT,'upload')
    os.chdir(path)
    file_list=[]
    extension='*.txt'
    file_list+=[os.path.realpath(e) for e in glob.glob(extension)]
    for fpath in file_list:
        os.remove(fpath)
    context = Context({
    'user':logoUser,
    'essay_type':EssayType.objects.all(),
    'vies':viewsList
    })
    return HttpResponse(template.render(context))

@csrf_exempt
def uploadify_script(request):
    response=HttpResponse()
    response['Content-Type']="text/javascript"
    ret="0"        
    file = request.FILES.get("Filedata",None)       
    if file:            
        if _upload(file):
            ret="1"
        ret="2"
    response.write(ret)
    return response
"""
def _upload(file):
    '''文件上传函数'''
    if file:            
        path=os.path.join(settings.MEDIA_ROOT,'upload')
        file_name=file.name    
        path_file=os.path.join(path,file_name)
        file_upload = open( path_file, 'ab+')
        for chunk in file.chunks():  
           file_upload.write(chunk)  
        file_upload.close()
        fpath=os.path.join(path,file_name.encode('gb18030'))
        fp=open(fpath,'rb')
        etype=EssayType.objects.get(id=6)
        essay=Essay()
        essay.title=file_name
        essay.content= fp.read().decode('gbk').encode('utf-8')
        essay.eType=etype
        essay.pub_date=datetime.datetime.now()
        essay.save()
        fp.close()
        return True
    return False"""
def _upload(file):
    '''文件上传函数'''
    if file:            
        path=os.path.join(settings.MEDIA_ROOT,'upload')
        file_name=file.name    
        path_file=os.path.join(path,file_name)
        file_upload = open( path_file, 'ab+')
        for chunk in file.chunks():  
           file_upload.write(chunk)  
        file_upload.close()
        return True
    return False
def mulpulish(request):
    if request.method == 'GET':
        etypename=request.GET.get('ETYPE',None)
        path=os.path.join(settings.MEDIA_ROOT,'upload')
        os.chdir(path)
        file_list=[]
        extension='*.txt'
        file_list+=[os.path.realpath(e) for e in glob.glob(extension)]
        if etypename :
            for fpath in file_list:
                fp=open(fpath,'rb')
                ptitle=fpath.split('\\')[-1]
                conlist=[]
                pcontent=fp.read().decode('gbk').encode('utf-8')
                if etypename == u'\u81ea\u52a8\u5206\u7c7b':
                    etypeid=classify(pcontent)
                    etypename=classs_list[etypeid]
                if etypename == u'\u672a\u9009\u62e9':
                    newtype=EssayType()
                    newtype.tname=request.GET.get('Newtype',None)
                    newtype.save()
                    etypename=newtype.tname
                etype=EssayType.objects.get(tname=etypename)

                essay=Essay()
                essay.title=ptitle
                essay.content= pcontent
                essay.eType=etype
                essay.pub_date=datetime.datetime.now()
                essay.save()
                fp.close()
                os.remove(fpath)
            return index(request)
        else:
            return HttpResponse('error1.')
    return HttpResponse('请勿重复提交')
def classify(text):
    import jieba
    all_words = {}  
    all_words_test = {} 
    word_cut=jieba.cut(text,cut_all=False) 
    word_list=list(word_cut)
    for word in word_list:
        if all_words_test.has_key(word):#if word in all_words.keys():  
                all_words_test[word] += 1  
        else:  
                all_words_test[word] = 0  
## 由于乱码的问题，没有正确使用 stopwords；简单去掉 前100个高频项  
## word_features 是选用的 word-词典 
    test_data = document_features(all_words_test.keys())
    classify_test = TextClassification(test_data) 
    return classify_test 




def words_dict_use_stopwords(deleteN):  
    #dict_name = "dict_stopwords_"+str(deleteN)+".txt"  
    #dict = open(dict_name, 'w') 
   # stopwords_file = open('D:\\texthub\\texthub\\managehub\\stopwords_cn.txt', 'r')  
   # stopwords_list = []  
   # for line in stopwords_file.readlines():  
        #print line.decode('gbk')  
   #     stopwords_list.append(line)
    #print stopwords_list  
    f=open('D:\\texthub\\texthub\\managehub\\words_list.txt','r')
    all_words_list=eval(f.read()) 
    f.close() 
    n = 0  
    word_features = []  
    for t in range(deleteN, len(all_words_list), 1):  
            if n > 1000:  
                        break  

texthub/managehub/templates/managehub/details.html
<!DOCTYPE html>

<html lang="zh-CN" dropeffect="none"  style="">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
{% load staticfiles %}
<meta charset="utf-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title>首页 - TextHub</title>
<link rel="stylesheet" href="/static/bd80dcc4ec449adf06670b068226708b.z.css" type="text/css" media="screen,print">
<link rel="stylesheet" href="/static/win-chrome-punctuation.css" type="text/css" media="screen,print">
<style type="text/css">
#sddm div a
	{	position: relative;
		display: block;
		margin: 0;
		padding: 5px 10px;
		width: auto;
		white-space: nowrap;
		text-align: left;
		background: #0267CC;
		color:#fff;
		font: 12px arial
		border-top:1px solid #0D5AA5;
		overflow:hidden}

	#sddm div a:hover
	{	background-color:#0267CC}
</style>
<style>
@font-face {
font-family: 'Helvetica Neue';
unicode-range: U+0600—06FF, U+0750—077F, U+08A0—08FF, U+FB50—FDFF, U+FE70—FEFF, U+10E60—10E7F, U+1EE00—1EEFF;
src: local(Arial);
}
@font-face {
font-family: 'Helvetica Neue';
font-weight: bold;
unicode-range: U+0600—06FF, U+0750—077F, U+08A0—08FF, U+FB50—FDFF, U+FE70—FEFF, U+10E60—10E7F, U+1EE00—1EEFF;
src: local(Arial);
}
</style>
<script type="text/javascript">
<!--
var timeout         = 500;
var closetimer		= 0;
var ddmenuitem      = 0;

// open hidden layer
function mopen(id)
{	
	// cancel close timer
	mcancelclosetime();

	// close old layer
	if(ddmenuitem) ddmenuitem.style.visibility = 'hidden';
	console.log("-----------------");
	// get new layer and show it
	ddmenuitem = document.getElementById(id);
	ddmenuitem.style.visibility = 'visible';

}
// close showed layer
function mclose()
{
	if(ddmenuitem) ddmenuitem.style.visibility = 'hidden';
}

// go close timer
function mclosetime()
{
	closetimer = window.setTimeout(mclose, timeout);
}

// cancel close timer
function mcancelclosetime()
{
	if(closetimer)
	{
		window.clearTimeout(closetimer);
		closetimer = null;
	}
}

// close layer when click-out
document.onclick = mclose; 
// -->

</script>

</head>

<body class="zhi" style="">
<div role="navigation" class="zu-top" style="">
<div class="zg-wrap" id="zh-top-inner" style="">


<div class="top-nav-profile" style="">
<a href="http://www.zhihu.com/people/zhao-li-66" class="zu-top-nav-userinfo " id=":0" role="button" aria-haspopup="true" aria-activedescendant="" style="" aria-expanded="false">
<span class="name" style="">{{user}}</span>
<img class="avatar" src="/static/6c3b2735f_s.jpg" style="">
<span id="zh-top-nav-new-pm" class="zg-noti-number zu-top-nav-pm-count" style="visibility: hidden;" data-count="0">
</span>
</a>
<ul class="top-nav-dropdown" id="top-nav-profile-dropdown" aria-labelledby=":0" style="" aria-hidden="true">
<li style="">
<a href="http://www.zhihu.com/logout" tabindex="-1" id=":4" style="">
<i class="zg-icon zg-icon-dd-logout" style=""></i>退出
</a>
</li>
</ul>
</div>
<div role="search" id="zh-top-search" class="zu-top-search" style="">
<form method="post" action="/search/" id="zh-top-search-form" class="zu-top-search-form form-with-magnify" style="">
{% csrf_token %}
<input type="text" class="zu-top-search-input" id="keyword" name="keyword" autocomplete="off" value="" aria-haspopup="true" style="">
<button type="submit" id="searchsubmit" class="zu-top-add-question" id="zu-top-add-question" style="">查询</button>
</form>

</div>
<div id="zg-top-nav" class="zu-top-nav" style="">
<ul class="zu-top-nav-ul zg-clear" style="">

<li class="zu-top-nav-li current" id="zh-top-home-link" style="">
<a class="zu-top-nav-link" href="/managehub/index/" id="zh-top-link-home" style="">首页</a>
</li>
<li class="zu-top-nav-li " style="">
<a class="zu-top-nav-link" href="/admin/"  target="_blank" style="">管理</a>
</li>
<li class="top-nav-topic-selector zu-top-nav-li " id="zh-top-nav-item-topic" style="">

<a class="zu-top-nav-link"  id="top-nav-dd-topic" href = "/fabu1/"   class="messages" onmouseover="mopen('m1')" onmouseout="mclosetime()">发布</a>
<div id="sddm">
<div id="m1" onmouseover="mcancelclosetime()" onmouseout="mclosetime()" style="position: absolute;visibility: hidden;margin: 0;padding: 0;background: #EAEBD8;border: 1px solid #5970B2">
<a  href = "/fabu1/"   class="messages" >发布</a>
<a  href = "/fabu/"   class="messages"  >批量发布</a>
</div>
</div>
</li>

</ul>
</div>
</div>

</div>
</div>
</div>
<div class="zg-wrap zu-main question-page" id="zh-single-question-page"  role="main">
<div class="zu-main-content" >

<!-- start of content -->
<div class="zu-main-content-inner" id="zh-single-question">
<div id="zh-question-title" class="zm-editable-status-normal">
<h2 class="zm-item-title zm-editable-content">{{essay.title}}</h2>
<br>
<span >属于<a href="/etype/{{essay.eType_id}}/" title="查看该类所有文章" rel="category">{{essay.eType}}</a>     发表于{{essay.pub_date.year}} .{{essay.pub_date.month}} .{{essay.pub_date.day}} {{essay.pub_date.hour}}:{{essay.pub_date.minute}}</span>
<br></br>
<div id="zh-question-detail" class="zm-item-rich-text zm-editable-status-normal" >
<div class="zm-editable-content">
{{essay.content}}
</div>
</div>
<br></br>
浏览: {{essay.view_count}}   次
</div>
</div>
<!-- end of content -->
<div class="zu-main-content-inner" style="">
<div class="zg-section" id="zh-home-list-title" style="">

<div id="light" class="white_content" style="display:none">



</div> 

</div>

</div>
</div>
<div class="zu-main-sidebar" style="">

<div class="zm-side-section" style="">
<div class="zm-side-section-inner" style="">
<div class="zm-side-nav-group" style="">
<ul class="zm-side-nav" id="zg-sidebar-nav" style="">
<li class="zm-side-nav-li" style="">
<a class="zm-side-nav-link" href="" style="">
<i class="zg-icon zg-icon-sidenav-draft" style=""></i>
我的分类
</a>
</li>
</ul>
</div>
{%for etype in essay_type%}
<a class="zm-side-nav-link" href="/etype/{{etype.id}}/" title="{{etype}}" style="">
<i class="zg-icon zg-icon-sidenav-draft" style=""></i>
{{etype}}({{etype.essay_set.count}})
</a>
{%endfor%}
</br>
<div class="zm-side-nav-group" style="">
<ul class="zm-side-nav" style="">
<li class="zm-side-nav-li" style="">
<a class="zm-side-nav-link" href="http://www.zhihu.com/log/questions" style="">
<i class="zg-icon zg-icon-sidenav-all" style=""></i>
经常浏览
</a>
</li>
</ul>
</div>
{%for vessay in vies%}
<a class="zm-side-nav-link" href="/essay/{{vessay.id}}/" style="">
<i class="zg-icon zg-icon-sidenav-draft" style=""></i>
{{vessay}}
</a>
{%endfor%}
</div>
</div>
<div id="zh-footer" class="zu-footer" style="">
<div class="zg-wrap zu-footer-inner" style="">
</div>
</div>



<input type="hidden" name="_xsrf" value="25563a936c5243b69cae14782ac99742" style="">

<div class="zh-backtotop" style="opacity: 1;">
	<a data-action="backtotop" data-tip="s$r$回到顶部" href="#top" class="btn-backtotop btn-action" style="">
		<div class="arrow" style="">
			
		</div>
		<div class="stick" style="">
		</div>
	</a>
</div>
<div id="zh-tooltip" style="visibility: hidden; left: 943px; top: 7195px; display: none;" class="tooltip right">
<div class="tooltip-arrow">
</div>
<div class="tooltip-inner" >回到顶部</div>
</div>
<div id="zh-global-spinner" style="display: none;">加载中…</div>
</body></html>

texthub/managehub/templates/managehub/logo.html
<!DOCTYPE html>
<html lang="zh-CN" class="no-touch no-mobile">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
{% load staticfiles %}
<meta charset="utf-8">
<title>TextHub</title>

<link rel="stylesheet" href="/static/style.css" type="text/css" media="screen,print">

<script async="" src="/static/analytics.js"></script>
<script type="text/javascript" async="" src="/static/ga.js">
</script>
</head>
<body class="no-auth" style="">



<div class="wrapper">
<div class="top">
<div class="inner-wrapper">
<div class="form-wrapper" id="js-form-wrapper">
<div class="logo"></div>

<div class="view view-signup selected" id="signup" style="display: block; ">
<form action="/logo/" method="get" class="zu-side-login-box" id="sign-form-1" autocomplete="off" novalidate="novalidate">
<br></br>
<div class="name input-wrapper js-weibo-bind-name-transfer">
<input required="" name='username' placeholder="用户">
</div>

<div class="input-wrapper">
<input required="" type="password" minlength="6" maxlength="128" name="password" placeholder="密码">
</div>
<div class="captcha-holder"></div>
<div class="button-wrapper command">
<button class="sign-button" type="submit">登陆</button>
</div>

</form>
</div>




<div class="mobi-front">


<div class="ft mobile">
</div>
</div>
</div>
</div>
</div>
<div class="bottom">
<div class="inner-wrapper">
<div class="stories zg-clear">





<div class="single-story" style="width:700px;">
<i class="icon-sign icon-sign-spike visible" style="top: 21px; "></i>

<div class="single-story-inner topic">
<div class="sep"></div>
* 名称: 汉语文本段落库管理系统
</br>
* 作用：方便用户管理自己的汉语文本段落，功能：类别区分，自动分类，查询文本段落，修改文本段落。
</br>
* 程序框架图：
</br>
<img src='/static/111.jpg'/>
</div>
</div>

</div>
</div>
</div>
</div>


</div>

<div id="zh-tooltip"></div></body></html>